# Generated by Django 4.2.30 on 2026-05-03 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(db_column='sync_log_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integration_type', models.CharField(choices=[('dhis2', 'DHIS2'), ('fhir', 'FHIR')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], max_length=20)),
                ('records_attempted', models.PositiveIntegerField(default=0)),
                ('records_synced', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('triggered_by', models.ForeignKey(blank=True, db_column='triggered_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'integration_sync_logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
