# Generated by Django 6.0.4 on 2026-05-05 15:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('immunizations', '0002_immunizationevent_local_client_record_id_and_more'),
        ('patients', '0002_patient_caregiver_user_account_offline_sync'),
        ('surveillance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(db_column='template_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_code', models.CharField(max_length=60, unique=True)),
                ('channel', models.CharField(choices=[('sms', 'SMS')], default='sms', max_length=10)),
                ('message_type', models.CharField(choices=[('reminder', 'Reminder'), ('missed_appointment', 'Missed Appointment'), ('outbreak_warning', 'Outbreak Warning'), ('welcome', 'Welcome'), ('manual', 'Manual')], max_length=30)),
                ('language_code', models.CharField(default='en', max_length=12)),
                ('template_body', models.TextField(help_text='Use {placeholders} e.g. {caregiver_name}, {patient_name}, {vaccine_name}, {due_date}, {facility_name}')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'message_templates',
            },
        ),
        migrations.CreateModel(
            name='SmsNotification',
            fields=[
                ('id', models.UUIDField(db_column='sms_notification_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('reminder', 'Reminder'), ('missed_appointment', 'Missed Appointment'), ('outbreak_warning', 'Outbreak Warning'), ('welcome', 'Welcome'), ('manual', 'Manual')], max_length=30)),
                ('phone_number', models.CharField(max_length=24)),
                ('language_code', models.CharField(default='en', max_length=12)),
                ('message_body', models.TextField()),
                ('priority', models.SmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('pending_retry', 'Pending Retry'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('gateway_message_id', models.CharField(blank=True, max_length=120, null=True)),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('caregiver', models.ForeignKey(db_column='caregiver_id', on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='patients.caregiver')),
                ('outbreak_alert', models.ForeignKey(blank=True, db_column='outbreak_alert_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_notifications', to='surveillance.outbreakalert')),
                ('patient', models.ForeignKey(blank=True, db_column='patient_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_notifications', to='patients.patient')),
                ('schedule_slot', models.ForeignKey(blank=True, db_column='patient_schedule_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_notifications', to='immunizations.patientvaccinationschedule')),
                ('template', models.ForeignKey(blank=True, db_column='template_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.messagetemplate')),
            ],
            options={
                'db_table': 'sms_notifications',
            },
        ),
        migrations.CreateModel(
            name='NotificationAttempt',
            fields=[
                ('id', models.UUIDField(db_column='notification_attempt_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.IntegerField()),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gateway_status_code', models.CharField(blank=True, max_length=40, null=True)),
                ('gateway_response', models.TextField(blank=True, null=True)),
                ('attempt_status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('retrying', 'Retrying')], max_length=12)),
                ('notification', models.ForeignKey(db_column='sms_notification_id', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='notifications.smsnotification')),
            ],
            options={
                'db_table': 'notification_attempts',
            },
        ),
        migrations.AddIndex(
            model_name='smsnotification',
            index=models.Index(fields=['status', 'scheduled_for'], name='sms_notific_status_7e8148_idx'),
        ),
        migrations.AddIndex(
            model_name='smsnotification',
            index=models.Index(fields=['patient', 'created_at'], name='sms_notific_patient_cefc60_idx'),
        ),
    ]
