# Generated by Django 6.0.4 on 2026-04-26 14:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeUnit',
            fields=[
                ('id', models.UUIDField(db_column='unit_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('country', 'Country'), ('region', 'Region'), ('zone', 'Zone'), ('woreda', 'Woreda'), ('kebele', 'Kebele')], max_length=20)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('boundary_geojson', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_unit_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='geography.administrativeunit')),
            ],
            options={
                'db_table': 'administrative_units',
            },
        ),
    ]
