# Generated by Django 4.2.30 on 2026-05-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeunit',
            name='area_sqkm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='bbox',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='data_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='name_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='source_dataset',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='valid_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='administrativeunit',
            index=models.Index(fields=['level'], name='administrat_level_aba368_idx'),
        ),
        migrations.AddIndex(
            model_name='administrativeunit',
            index=models.Index(fields=['parent'], name='administrat_parent__f28f9e_idx'),
        ),
    ]
