# Generated by Django 6.0.4 on 2026-04-26 14:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Antigen',
            fields=[
                ('id', models.UUIDField(db_column='antigen_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'antigens',
            },
        ),
        migrations.CreateModel(
            name='EpiScheduleVersion',
            fields=[
                ('id', models.UUIDField(db_column='schedule_version_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_name', models.CharField(max_length=80, unique=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'epi_schedule_versions',
            },
        ),
        migrations.CreateModel(
            name='VaccineDefinition',
            fields=[
                ('id', models.UUIDField(db_column='vaccine_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vaccine_code', models.CharField(max_length=40, unique=True)),
                ('vaccine_name', models.CharField(max_length=120)),
                ('dose_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('default_route', models.CharField(blank=True, max_length=40, null=True)),
                ('default_site', models.CharField(blank=True, max_length=40, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('antigen', models.ForeignKey(blank=True, db_column='antigen_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vaccines', to='vaccines.antigen')),
            ],
            options={
                'db_table': 'vaccine_definitions',
            },
        ),
        migrations.CreateModel(
            name='VaccineBatch',
            fields=[
                ('id', models.UUIDField(db_column='vaccine_batch_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=80, unique=True)),
                ('manufacturer_name', models.CharField(blank=True, max_length=120, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('source_system', models.CharField(blank=True, max_length=80, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vaccine', models.ForeignKey(db_column='vaccine_id', on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='vaccines.vaccinedefinition')),
            ],
            options={
                'db_table': 'vaccine_batches',
            },
        ),
        migrations.CreateModel(
            name='EpiScheduleRule',
            fields=[
                ('id', models.UUIDField(db_column='schedule_rule_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dose_label', models.CharField(max_length=60)),
                ('recommended_age_days', models.PositiveIntegerField()),
                ('grace_period_days', models.PositiveIntegerField(default=0)),
                ('defaulter_threshold_days', models.PositiveIntegerField(default=7)),
                ('medical_exception_rule', models.JSONField(blank=True, null=True)),
                ('is_birth_dose', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule_version', models.ForeignKey(db_column='schedule_version_id', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='vaccines.epischeduleversion')),
                ('vaccine', models.ForeignKey(db_column='vaccine_id', on_delete=django.db.models.deletion.PROTECT, related_name='schedule_rules', to='vaccines.vaccinedefinition')),
            ],
            options={
                'db_table': 'epi_schedule_rules',
                'unique_together': {('schedule_version', 'vaccine', 'dose_label')},
            },
        ),
    ]
