# Generated by Django 4.2.30 on 2026-05-03 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRegenerationJob',
            fields=[
                ('id', models.UUIDField(db_column='schedule_regeneration_job_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(blank=True, max_length=160, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('total', models.PositiveIntegerField(default=0)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, db_column='requested_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_regeneration_jobs', to=settings.AUTH_USER_MODEL)),
                ('schedule_version', models.ForeignKey(db_column='schedule_version_id', on_delete=django.db.models.deletion.CASCADE, related_name='regeneration_jobs', to='vaccines.epischeduleversion')),
            ],
            options={
                'db_table': 'schedule_regeneration_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
