# Generated by Django 6.0.4 on 2026-04-18 13:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.UUIDField(db_column='facility_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('facility_code', models.CharField(max_length=32, unique=True)),
                ('facility_name', models.CharField(max_length=160)),
            ],
            options={
                'db_table': 'health_facilities',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(db_column='role_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_code', models.CharField(max_length=40, unique=True)),
                ('role_name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(db_column='user_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=160, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('must_change_password', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('locked', 'Locked'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], default='inactive', max_length=16)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('preferred_language', models.CharField(default='en', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('assigned_facility', models.ForeignKey(blank=True, db_column='assigned_facility_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='users.healthfacility')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.role')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
