# Generated by Django 6.0.4 on 2026-04-26 14:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(db_column='patient_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(editable=False, max_length=40, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('middle_name', models.CharField(blank=True, max_length=80, null=True)),
                ('last_name', models.CharField(blank=True, max_length=80, null=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('medical_exception_flag', models.BooleanField(default=False)),
                ('duplicate_review_status', models.CharField(choices=[('clear', 'Clear'), ('suspected', 'Suspected'), ('confirmed_duplicate', 'Confirmed Duplicate'), ('merged', 'Merged')], default='clear', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('verifying', 'Verifying'), ('registered', 'Registered'), ('merged', 'Merged'), ('inactive', 'Inactive'), ('deceased', 'Deceased')], default='registered', max_length=16)),
                ('qr_code_value', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.UUIDField(db_column='caregiver_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=160)),
                ('phone_number', models.CharField(max_length=24)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=24, null=True)),
                ('relationship_to_patient', models.CharField(max_length=60)),
                ('preferred_language', models.CharField(default='am', max_length=12)),
                ('address_line', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('residence_unit', models.ForeignKey(blank=True, db_column='residence_unit_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caregivers', to='geography.administrativeunit')),
            ],
            options={
                'db_table': 'caregivers',
            },
        ),
        migrations.CreateModel(
            name='PatientImmunizationStatus',
            fields=[
                ('patient', models.OneToOneField(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='immunization_status', serialize=False, to='patients.patient')),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('up_to_date', 'Up to Date'), ('due_soon', 'Due Soon'), ('overdue', 'Overdue'), ('defaulter', 'Defaulter'), ('zero_dose', 'Zero Dose'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('due_count', models.PositiveIntegerField(default=0)),
                ('overdue_count', models.PositiveIntegerField(default=0)),
                ('administered_count', models.PositiveIntegerField(default=0)),
                ('is_zero_dose', models.BooleanField(default=True)),
                ('last_evaluated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'patient_immunization_status',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='primary_caregiver',
            field=models.ForeignKey(db_column='primary_caregiver_id', on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='patients.caregiver'),
        ),
        migrations.AddField(
            model_name='patient',
            name='registered_by',
            field=models.ForeignKey(blank=True, db_column='registered_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='registered_facility',
            field=models.ForeignKey(blank=True, db_column='registered_facility_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to='users.healthfacility'),
        ),
        migrations.AddField(
            model_name='patient',
            name='residence_unit',
            field=models.ForeignKey(blank=True, db_column='residence_unit_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='geography.administrativeunit'),
        ),
    ]
