# Generated by Django 6.0.4 on 2026-04-29 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='user_account',
            field=models.OneToOneField(blank=True, db_column='user_account_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caregiver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='user_account',
            field=models.OneToOneField(blank=True, db_column='user_account_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
