# Generated by Django 4.2.30 on 2026-05-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_caregiver_user_account_offline_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='local_client_record_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='local_client_record_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
