# Generated by Django 6.0.4 on 2026-04-29 14:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRegistration',
            fields=[
                ('id', models.UUIDField(db_column='device_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_label', models.CharField(max_length=120)),
                ('platform', models.CharField(max_length=40)),
                ('app_version', models.CharField(blank=True, max_length=40, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=10)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_registrations',
            },
        ),
        migrations.CreateModel(
            name='SyncBatch',
            fields=[
                ('id', models.UUIDField(db_column='sync_batch_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('processed', 'Processed'), ('conflict', 'Conflict'), ('rejected', 'Rejected')], default='submitted', max_length=10)),
                ('record_count', models.IntegerField(default=0)),
                ('conflict_count', models.IntegerField(default=0)),
                ('device', models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, related_name='sync_batches', to='offline.deviceregistration')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='sync_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_batches',
            },
        ),
        migrations.CreateModel(
            name='SyncBatchItem',
            fields=[
                ('id', models.UUIDField(db_column='sync_batch_item_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('patient', 'Patient'), ('immunization', 'Immunization'), ('surveillance_report', 'Surveillance Report'), ('caregiver', 'Caregiver')], max_length=40)),
                ('operation_type', models.CharField(choices=[('insert', 'Insert'), ('update', 'Update')], max_length=10)),
                ('client_record_id', models.CharField(max_length=120)),
                ('server_record_id', models.UUIDField(blank=True, null=True)),
                ('item_status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('conflict', 'Conflict'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('conflict_reason', models.TextField(blank=True, null=True)),
                ('payload_checksum', models.CharField(blank=True, max_length=128, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('batch', models.ForeignKey(db_column='sync_batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='offline.syncbatch')),
            ],
            options={
                'db_table': 'sync_batch_items',
            },
        ),
    ]
