# Generated by Django 4.2.30 on 2026-05-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline', '0001_patient_caregiver_user_account_offline_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncbatchitem',
            name='entity_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('immunization', 'Immunization'), ('immunization_event', 'Immunization Event'), ('surveillance_report', 'Surveillance Report'), ('caregiver', 'Caregiver')], max_length=40),
        ),
    ]
