# Generated by Django 4.2.30 on 2026-05-02 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('user_create', 'User Create'), ('user_update', 'User Update'), ('user_deactivate', 'User Deactivate'), ('user_status_update', 'User Status Update'), ('role_assign', 'Role Assign'), ('account_unlock', 'Account Unlock'), ('patient_create', 'Patient Create'), ('patient_delete', 'Patient Delete'), ('outbreak_alert_confirm', 'Outbreak Alert Confirm')], max_length=40)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(max_length=120)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action'], name='audit_logs_action_31f574_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx'), models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx')],
            },
        ),
    ]
