#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from pathlib import Path


DOC_ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = DOC_ROOT / "REPORT_ASSEMBLY_MANIFEST.json"
OUTPUT_PATH = DOC_ROOT / "build" / "FinalYearProjectReport.reconstructed.md"


def strip_auto_note(text: str) -> str:
    lines = text.splitlines()
    if lines and lines[0].startswith("<!-- Auto-generated by documentation/tools/dissect_report.py"):
        return "\n".join(lines[2:]).strip()
    return text.strip()


def rewrite_relative_links(text: str, source_path: Path) -> str:
    def replacer(match: re.Match[str]) -> str:
        target = match.group(1)
        if target.startswith(("http://", "https://", "#", "/")):
            return match.group(0)

        resolved = (source_path.parent / target).resolve()
        try:
            rewritten = resolved.relative_to(DOC_ROOT)
            final = Path("..") / rewritten
            return f"]({final.as_posix()})"
        except ValueError:
            return match.group(0)

    return re.sub(r"\]\(([^)]+)\)", replacer, text)


def main() -> None:
    if not MANIFEST_PATH.exists():
        raise FileNotFoundError(
            "Missing REPORT_ASSEMBLY_MANIFEST.json. Run documentation/tools/dissect_report.py first."
        )

    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    chunks: list[str] = [
        "<!-- Reconstructed from dissected report files. Regenerate with documentation/tools/assemble_report.py. -->",
        "",
        f"# {manifest.get('title', 'Reconstructed Report')}",
        "",
    ]

    for item in manifest.get("ordered_files", []):
        source_path = DOC_ROOT / item["path"]
        if not source_path.exists():
            continue
        content = strip_auto_note(source_path.read_text(encoding="utf-8"))
        chunks.append(rewrite_relative_links(content, source_path))
        chunks.append("")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(chunks).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
