#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import re
import shutil
from collections import defaultdict
from pathlib import Path

from bs4 import BeautifulSoup, Tag


DOC_ROOT = Path(__file__).resolve().parents[1]
PROJECT_ROOT = DOC_ROOT.parent

SOURCE_HTML_CANDIDATES = [
    Path("/Users/tikursew/Downloads/Final year Project Report/FinalyearProjectReport.html"),
    PROJECT_ROOT / "paper/Final year Project Report 1-3/FinalyearProjectReport13.html",
]
SOURCE_DOCX = PROJECT_ROOT / "paper/Final year Project Report.docx"
SOURCE_GUIDELINE = PROJECT_ROOT / "paper/Senior Research Project Document Guideline.pdf"

SOURCE_ASSET_DIR = DOC_ROOT / "assets" / "source-files" / "original-report"
SOURCE_IMAGE_DIR = DOC_ROOT / "assets" / "images" / "report-original"
MERMAID_DIR = DOC_ROOT / "assets" / "diagrams" / "mermaid"
BUILD_DIR = DOC_ROOT / "build"

AUTO_NOTE = (
    "<!-- Auto-generated by documentation/tools/dissect_report.py. "
    "Edit the source report or this generator, then rerun the script. -->\n\n"
)


SECTION_PATHS = {
    "cover": DOC_ROOT / "01-front-matter/01-cover-and-title-page/report-source.md",
    "ack": DOC_ROOT / "01-front-matter/02-acknowledgement/report-source.md",
    "toc_lists": DOC_ROOT / "01-front-matter/03-table-of-contents-and-lists/report-source.md",
    "abstract": DOC_ROOT / "01-front-matter/04-abstract/report-source.md",
    "ch1": DOC_ROOT / "02-chapter-1-introduction/chapter-source.md",
    "1.1": DOC_ROOT / "02-chapter-1-introduction/01-statement-of-the-problem/report-source.md",
    "1.2": DOC_ROOT / "02-chapter-1-introduction/02-objectives/report-source.md",
    "1.3": DOC_ROOT / "02-chapter-1-introduction/03-scope-and-limitation/report-source.md",
    "1.4": DOC_ROOT / "02-chapter-1-introduction/04-methodology/report-source.md",
    "1.5": DOC_ROOT / "02-chapter-1-introduction/05-plan-of-activities/report-source.md",
    "1.6": DOC_ROOT / "02-chapter-1-introduction/06-budget-required/report-source.md",
    "1.7": DOC_ROOT / "02-chapter-1-introduction/07-significance-of-the-study/report-source.md",
    "1.8": DOC_ROOT / "02-chapter-1-introduction/08-outline-of-the-study/report-source.md",
    "ch2": DOC_ROOT / "03-chapter-2-literature-review/chapter-source.md",
    "2.1": DOC_ROOT / "03-chapter-2-literature-review/01-study-related-works/report-source.md",
    "2.2": DOC_ROOT / "03-chapter-2-literature-review/02-milestones-and-gaps/report-source.md",
    "2.3": DOC_ROOT / "03-chapter-2-literature-review/03-lessons-learned/report-source.md",
    "ch3": DOC_ROOT / "04-chapter-3-problem-analysis-and-modeling/chapter-source.md",
    "3.1": DOC_ROOT / "04-chapter-3-problem-analysis-and-modeling/01-existing-system-and-problems/report-source.md",
    "3.2": DOC_ROOT / "04-chapter-3-problem-analysis-and-modeling/02-requirements-elicitation/report-source.md",
    "3.3.1": DOC_ROOT / "04-chapter-3-problem-analysis-and-modeling/03-functional-requirements/report-source.md",
    "3.3.2": DOC_ROOT / "04-chapter-3-problem-analysis-and-modeling/04-non-functional-requirements/report-source.md",
    "3.3.3": DOC_ROOT / "04-chapter-3-problem-analysis-and-modeling/05-use-case-models/report-source.md",
    "3.3.4": DOC_ROOT / "04-chapter-3-problem-analysis-and-modeling/06-dynamic-models/report-source.md",
    "3.5": DOC_ROOT / "04-chapter-3-problem-analysis-and-modeling/07-model-validation/report-source.md",
    "ch4": DOC_ROOT / "05-chapter-4-system-design/chapter-source.md",
    "4.1-4.2": DOC_ROOT / "05-chapter-4-system-design/01-overview-and-design-goals/report-source.md",
    "4.3.1": DOC_ROOT / "05-chapter-4-system-design/02-software-architecture/report-source.md",
    "4.3.2": DOC_ROOT / "05-chapter-4-system-design/03-subsystem-decomposition/report-source.md",
    "references": DOC_ROOT / "09-references/report-source.md",
}


MANIFEST_ORDER = [
    "cover",
    "ack",
    "toc_lists",
    "abstract",
    "ch1",
    "1.1",
    "1.2",
    "1.3",
    "1.4",
    "1.5",
    "1.6",
    "1.7",
    "1.8",
    "ch2",
    "2.1",
    "2.2",
    "2.3",
    "ch3",
    "3.1",
    "3.2",
    "3.3.1",
    "3.3.2",
    "3.3.3",
    "3.3.4",
    "3.5",
    "ch4",
    "4.1-4.2",
    "4.3.1",
    "4.3.2",
    "references",
]


ACTIVITY_TITLES = {
    "Activity Diagram for User Management and Security",
    "Activity Diagram for Patient and Caregiver Registration",
    "Activity Diagram for Immunization and Surveillance Management",
    "Activity Diagram for Notifications and Alerts",
    "Activity Diagram for Predictive Analytics and Decision Support",
    "Activity Diagram for Reporting and Interoperability",
}


def normalize_text(value: str) -> str:
    value = value.replace("\xa0", " ")
    value = re.sub(r"\s+", " ", value)
    return value.strip()


def clean_heading_text(value: str) -> str:
    value = normalize_text(value)
    value = value.lstrip("_").strip()
    value = value.replace("  ", " ")
    return value


def slugify(value: str) -> str:
    value = value.lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    return value.strip("-")


def resolve_source_html() -> Path:
    for candidate in SOURCE_HTML_CANDIDATES:
        if candidate.exists():
            return candidate
    raise FileNotFoundError("Could not locate the source HTML export for the report.")


def ensure_source_assets(source_html: Path) -> None:
    SOURCE_ASSET_DIR.mkdir(parents=True, exist_ok=True)
    SOURCE_IMAGE_DIR.mkdir(parents=True, exist_ok=True)
    MERMAID_DIR.mkdir(parents=True, exist_ok=True)
    BUILD_DIR.mkdir(parents=True, exist_ok=True)

    shutil.copy2(source_html, SOURCE_ASSET_DIR / source_html.name)
    if SOURCE_DOCX.exists():
        shutil.copy2(SOURCE_DOCX, SOURCE_ASSET_DIR / SOURCE_DOCX.name)
    if SOURCE_GUIDELINE.exists():
        shutil.copy2(SOURCE_GUIDELINE, SOURCE_ASSET_DIR / SOURCE_GUIDELINE.name)

    source_images = source_html.parent / "images"
    if source_images.exists():
        for image_file in source_images.iterdir():
            if image_file.is_file():
                shutil.copy2(image_file, SOURCE_IMAGE_DIR / image_file.name)


def group_for_heading(text: str) -> str | None:
    text = clean_heading_text(text)

    if not text:
        return None
    if text == "Acknowledgement":
        return "ack"
    if text in {"Table of Contents", "List of Tables", "List of Figures", "List of Abbreviations"}:
        return "toc_lists"
    if text == "Abstract":
        return "abstract"
    if text.startswith("Chapter One: Introduction"):
        return "ch1"
    if text.startswith("1.1"):
        return "1.1"
    if text.startswith("1.2"):
        return "1.2"
    if text.startswith("1.3"):
        return "1.3"
    if text.startswith("1.4"):
        return "1.4"
    if text.startswith("1.5"):
        return "1.5"
    if text.startswith("1.6"):
        return "1.6"
    if text.startswith("1.7"):
        return "1.7"
    if text.startswith("1.8"):
        return "1.8"
    if text.startswith("Chapter Two: Literature Review"):
        return "ch2"
    if text.startswith("2.1") or text.startswith("A. ") or text.startswith("B. ") or text.startswith("C. "):
        return "2.1"
    if text.startswith("2.2"):
        return "2.2"
    if text.startswith("2.3"):
        return "2.3"
    if text.startswith("Chapter Three: Problem Analysis and Modeling"):
        return "ch3"
    if text.startswith("3.0"):
        return "ch3"
    if text.startswith("3.1"):
        return "3.1"
    if text.startswith("3.2"):
        return "3.2"
    if text.startswith("3.3 System Modeling"):
        return "3.3.1"
    if text.startswith("3.3.1"):
        return "3.3.1"
    if text.startswith("3.3.2"):
        return "3.3.2"
    if text.startswith("3.3.3"):
        return "3.3.3"
    if text.startswith("3.3.4") or text in ACTIVITY_TITLES:
        return "3.3.4"
    if text.startswith("3.5"):
        return "3.5"
    if text.startswith("CHAPTER FOUR: SYSTEM DESIGN"):
        return "ch4"
    if text.startswith("4.1") or text.startswith("4.2"):
        return "4.1-4.2"
    if text.startswith("4.3. System Design"):
        return "ch4"
    if text.startswith("4.3.1") or text.startswith("Architecture Overview"):
        return "4.3.1"
    if text.startswith("4.3.2"):
        return "4.3.2"
    if text == "References":
        return "references"
    return None


def heading_level(text: str, is_first_in_group: bool) -> int:
    if is_first_in_group:
        return 1
    text = clean_heading_text(text)
    if text.startswith("Chapter ") or text.startswith("CHAPTER ") or text == "References":
        return 1
    if text in {"Acknowledgement", "List of Tables", "List of Figures", "List of Abbreviations", "Abstract"}:
        return 1
    if text == "Table of Contents":
        return 1
    if text in ACTIVITY_TITLES or text.startswith("Architecture Overview"):
        return 2
    match = re.match(r"^(\d+(?:\.\d+)*)", text)
    if match:
        depth = len(match.group(1).split("."))
        return min(max(depth, 1), 6)
    if re.match(r"^[A-Z]\.", text):
        return 2
    return 2


def normalize_inline_text(text: str) -> str:
    text = normalize_text(text)
    return text.replace(" .", ".").replace(" ,", ",").replace(" ;", ";").replace(" :", ":")


def escape_table_cell(value: str) -> str:
    return value.replace("|", "\\|")


def format_paragraph(text: str) -> str:
    if not text:
        return ""
    if text == "Image":
        return ""
    if re.fullmatch(r"\d+", text):
        return ""
    if text.startswith("Figure ") or text.startswith("Table "):
        return f"*{text}*\n"
    return f"{text}\n"


def convert_list(tag: Tag) -> str:
    items: list[str] = []
    for index, li in enumerate(tag.find_all("li", recursive=False), start=1):
        text = normalize_inline_text(li.get_text(" ", strip=True))
        if not text:
            continue
        prefix = f"{index}." if tag.name == "ol" else "-"
        items.append(f"{prefix} {text}")
    if not items:
        return ""
    return "\n".join(items) + "\n"


def convert_table(tag: Tag) -> str:
    rows: list[list[str]] = []
    for tr in tag.find_all("tr"):
        cells = tr.find_all(["th", "td"])
        row = [normalize_inline_text(cell.get_text(" ", strip=True)) for cell in cells]
        if any(row):
            rows.append(row)
    if not rows:
        return ""

    width = max(len(row) for row in rows)
    normalized_rows = [row + [""] * (width - len(row)) for row in rows]
    header = normalized_rows[0]
    if len(normalized_rows) == 1:
        header = [f"Column {i}" for i in range(1, width + 1)]
        normalized_rows.insert(0, header)

    lines = [
        "| " + " | ".join(escape_table_cell(cell) for cell in normalized_rows[0]) + " |",
        "| " + " | ".join("---" for _ in normalized_rows[0]) + " |",
    ]
    for row in normalized_rows[1:]:
        lines.append("| " + " | ".join(escape_table_cell(cell) for cell in row) + " |")
    return "\n".join(lines) + "\n"


def convert_image(tag: Tag, current_output: Path) -> str:
    src = (tag.get("src") or "").strip()
    if not src:
        return ""
    image_name = Path(src).name
    target = SOURCE_IMAGE_DIR / image_name
    proper_rel = Path(os.path.relpath(target, start=current_output.parent))
    alt = f"Source figure {image_name}"
    return f"![{alt}]({proper_rel.as_posix()})\n"


def render_block(tag: Tag, current_group: str) -> str:
    text = normalize_inline_text(tag.get_text(" ", strip=True))
    if tag.name == "p":
        return format_paragraph(text)
    if tag.name in {"ul", "ol"}:
        return convert_list(tag)
    if tag.name == "table":
        return convert_table(tag)
    return ""


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def build_sections(source_html: Path) -> tuple[dict[str, str], dict[str, list[str]]]:
    soup = BeautifulSoup(source_html.read_text(encoding="utf-8", errors="ignore"), "html.parser")
    sections: dict[str, list[str]] = defaultdict(list)
    section_headings: dict[str, list[str]] = defaultdict(list)
    current_group = "cover"

    body_children = [node for node in soup.body.children if isinstance(node, Tag)]

    for tag in body_children:
        nested_images = tag.find_all("img") if tag.name != "img" else []

        if tag.name in {"h1", "h2", "h3", "h4", "h5", "h6"}:
            text = clean_heading_text(tag.get_text(" ", strip=True))
            if not text:
                if current_group in SECTION_PATHS:
                    for image in nested_images:
                        sections[current_group].append(convert_image(image, SECTION_PATHS[current_group]))
                continue
            mapped_group = group_for_heading(text)
            if mapped_group:
                current_group = mapped_group
            if current_group not in SECTION_PATHS:
                continue
            level = heading_level(text, not sections[current_group])
            sections[current_group].append(f'{"#" * level} {text}\n')
            section_headings[current_group].append(text)
            for image in nested_images:
                sections[current_group].append(convert_image(image, SECTION_PATHS[current_group]))
            continue

        if tag.name == "p":
            text = normalize_inline_text(tag.get_text(" ", strip=True))
            if not text:
                if current_group in SECTION_PATHS:
                    for image in nested_images:
                        sections[current_group].append(convert_image(image, SECTION_PATHS[current_group]))
                continue
            if text == "Table of Contents":
                current_group = "toc_lists"
                level = heading_level(text, not sections[current_group])
                sections[current_group].append(f'{"#" * level} {text}\n')
                section_headings[current_group].append(text)
                continue
            if (
                current_group in {"ch4", "4.1-4.2", "4.3.1"}
                and (text.startswith("A. Architecture Overview") or text.startswith("1. Architecture Overview"))
            ):
                current_group = "4.3.1"
                level = heading_level("Architecture Overview (4-Tier Layered SOA)", not sections[current_group])
                sections[current_group].append(f'{"#" * level} Architecture Overview (4-Tier Layered SOA)\n')
                section_headings[current_group].append("Architecture Overview (4-Tier Layered SOA)")
                continue

        if current_group not in SECTION_PATHS:
            continue

        if tag.name == "img":
            sections[current_group].append(convert_image(tag, SECTION_PATHS[current_group]))
            continue

        for image in nested_images:
            sections[current_group].append(convert_image(image, SECTION_PATHS[current_group]))

        block = render_block(tag, current_group)
        if block:
            sections[current_group].append(block)

    materialized = {key: "\n".join(value).strip() for key, value in sections.items() if value}
    return materialized, section_headings


def build_manifest(section_headings: dict[str, list[str]]) -> dict[str, object]:
    ordered_files = []
    for key in MANIFEST_ORDER:
        path = SECTION_PATHS[key]
        if path.exists():
            ordered_files.append(
                {
                    "key": key,
                    "path": path.relative_to(DOC_ROOT).as_posix(),
                    "headings": section_headings.get(key, []),
                }
            )

    return {
        "title": "National Vaccination and Outbreak Monitoring System for Ethiopia",
        "source_html": next((p.name for p in SOURCE_ASSET_DIR.glob("*.html")), None),
        "ordered_files": ordered_files,
    }


MERMAID_TEMPLATES = {
    "figure-1-01-plan-of-activities-gantt.mmd": """gantt
    title Plan of Activities
    dateFormat  YYYY-MM-DD
    axisFormat  %Y-%m
    section Phase 1: System Analysis and Requirements
    Literature Review & Process Mapping :done, p1a, 2025-10-05, 14d
    Requirements Definition :done, p1b, after p1a, 14d
    Documentation :done, p1c, after p1b, 14d
    section Phase 2: System and Architecture Design
    System Architecture Design :active, p2a, 2025-11-20, 12d
    Data Architecture & Flow Design :p2b, after p2a, 12d
    Model Selection & Specification :p2c, after p2b, 7d
    section Phase 3: Development and Model Implementation
    Data Management Module Development :p3a, 2025-12-28, 14d
    Outbreak Prediction Module Implementation :p3b, after p3a, 14d
    Visualization & Alerting Interface :p3c, after p3b, 14d
    Module Testing :p3d, after p3c, 14d
    section Phase 4: Integration, Testing, and Evaluation
    System Integration :p4a, 2026-02-22, 12d
    System & Model Testing :p4b, after p4a, 18d
    User Acceptance Testing & Documentation :p4c, after p4b, 18d
""",
    "figure-3-01-use-case-diagram.mmd": """flowchart LR
    admin[Administrator]
    hw[Health Worker]
    cg[Caregiver]
    smsgw[SMS Gateway]
    dhis2[DHIS2]
    pho[Public Health Official]

    subgraph system["National Vaccination and Outbreak Monitoring System"]
      auth(("Authenticate User"))
      manage(("Manage User Accounts"))
      config(("Configure System Settings"))
      register(("Register Patient"))
      viewRecord(("View Patient Immunization Record"))
      recordVax(("Record Vaccine Administration"))
      epiData(("Update Epidemiological Data"))
      genSchedule(("Generate Vaccination Schedule"))
      monitor(("Monitor Vaccination Status"))
      identify(("Identify Defaulter"))
      reminder(("Send Vaccination Reminder"))
      missed(("Send Missed Appointment"))
      recvReminder(("Receive Vaccination Reminder SMS"))
      recvMissed(("Receive Missed Appointment"))
      dashboard(("View Analytics Dashboard"))
      riskMap(("View Outbreak Risk Map"))
      reports(("Generate/Export Reports"))
      predict(("Predict Disease Outbreak"))
      detect(("Detect High Defaulter"))
      share(("Share Immunization Data"))
      exchange(("Exchange Health Data (FHIR-compliant)"))
    end

    admin --> auth
    admin --> manage
    admin --> config
    admin --> register
    admin --> viewRecord
    admin --> recordVax
    admin --> epiData
    admin --> dashboard
    admin --> riskMap
    admin --> reports

    hw --> auth
    hw --> register
    hw --> viewRecord
    hw --> recordVax
    hw --> epiData
    hw --> monitor
    hw --> identify
    hw --> dashboard

    monitor --> identify
    register --> genSchedule
    identify --> missed
    genSchedule --> reminder
    predict --> dashboard
    predict --> riskMap
    detect --> reminder

    reminder --> smsgw
    missed --> smsgw
    smsgw --> recvReminder
    smsgw --> recvMissed
    cg --> recvReminder
    cg --> recvMissed
    dhis2 --> exchange
    share --> dhis2
    exchange --> dhis2
    pho --> dashboard
    pho --> riskMap
    pho --> reports
""",
    "figure-3-02-sequence-user-management-and-security.mmd": """sequenceDiagram
    actor Administrator
    actor HealthWorker as "Health Worker"
    participant WebPortal as "Web Portal"
    participant AuthService as "Auth Service"
    participant AccessControl as "Access Control"
    participant CentralDB as "Central Database"
    participant EmailService as "Email Service"

    rect rgb(255, 248, 180)
    Note over Administrator,CentralDB: FR1: Role-Based Account Creation
    Administrator->>WebPortal: Create account (role=HealthWorker)
    WebPortal->>AuthService: POST /users/create
    AuthService->>AccessControl: Validate admin permissions
    AccessControl-->>AuthService: Authorized
    AuthService->>CentralDB: Check if email exists
    CentralDB-->>AuthService: Unique
    AuthService->>AuthService: Hash password (Argon2)
    AuthService->>CentralDB: Insert user record
    CentralDB-->>AuthService: User ID created
    AuthService-->>WebPortal: Success message
    WebPortal-->>Administrator: Display "Account Created"
    end

    rect rgb(255, 248, 180)
    Note over HealthWorker,CentralDB: FR2 & FR3: Secure Authentication
    HealthWorker->>WebPortal: Input credentials
    WebPortal->>AuthService: Login(email, password)
    AuthService->>CentralDB: Fetch password hash
    CentralDB-->>AuthService: Return hash
    alt Credentials valid
      AuthService->>AuthService: Generate JWT token
      AuthService-->>WebPortal: 200 OK + token
      WebPortal-->>HealthWorker: Redirect to dashboard
    else Invalid password
      AuthService-->>WebPortal: 401 Unauthorized
      WebPortal-->>HealthWorker: Show error "Invalid Login"
    end
    opt FR3: Password recovery
      HealthWorker->>WebPortal: Request password reset
      WebPortal->>AuthService: Initiate reset flow
      AuthService->>EmailService: Send reset link
      EmailService-->>HealthWorker: Email with token
    end
""",
    "figure-3-03-sequence-patient-registration.mmd": """sequenceDiagram
    actor HealthWorker as "Health Worker"
    participant WebPortal as "Web Portal"
    participant Registration as "Registration Service"
    participant UID as "UID Generator"
    participant CentralDB as "Central Database"

    Note over HealthWorker,CentralDB: FR4-FR6: Core Registry and UID Generation
    HealthWorker->>WebPortal: Submit registration (patient + caregiver)
    WebPortal->>WebPortal: Validate mandatory fields
    WebPortal->>Registration: POST /patients/register
    Registration->>CentralDB: Check duplicates (name, location)
    CentralDB-->>Registration: No match found
    par Generate UID and format
      Registration->>UID: Request unique ID (e.g. ETH-1001)
      UID-->>Registration: Return UID
      Registration->>Registration: Format as FHIR Patient
    end
    Registration->>CentralDB: Begin transaction
    Registration->>CentralDB: Insert caregiver entity
    Registration->>CentralDB: Insert patient entity (linked)
    Registration->>CentralDB: Commit transaction
    CentralDB-->>Registration: Success (entities linked)
    Registration->>CentralDB: Initialize empty vaccination history
    CentralDB-->>Registration: History created
    Registration-->>WebPortal: Registration successful
    WebPortal-->>HealthWorker: Display patient dashboard
""",
    "figure-3-04-sequence-immunization-and-surveillance.mmd": """sequenceDiagram
    actor HealthWorker as "Health Worker"
    participant LocalStorage as "Local Storage (Device)"
    participant SyncService as "Sync Service"
    participant Immunization as "Immunization Service"
    participant CentralDB as "Central Database"

    Note over HealthWorker,CentralDB: FR7-FR11: Offline Data Capture and Sync
    HealthWorker->>LocalStorage: Record dose + observation
    LocalStorage->>LocalStorage: Save locally (status=pending)
    LocalStorage-->>HealthWorker: Saved offline

    opt Connectivity restored
      HealthWorker->>SyncService: Trigger manual/auto sync
      SyncService->>LocalStorage: Fetch pending records
      LocalStorage-->>SyncService: Return records JSON
      loop Process each record
        SyncService->>Immunization: Process vaccination event
        Immunization->>CentralDB: Save dose & observation
        CentralDB-->>Immunization: ACK
        Immunization->>Immunization: Calculate next due date (EPI rules)
        Immunization->>CentralDB: Update patient schedule
        alt Overdue
          Immunization->>CentralDB: Flag as defaulter
        else On time
          Immunization->>CentralDB: Clear defaulter flag
        end
      end
      Immunization-->>SyncService: Success
      SyncService->>LocalStorage: Clear synced records
      SyncService-->>HealthWorker: Sync complete
    end
""",
    "figure-3-05-sequence-notifications-and-alerts.mmd": """sequenceDiagram
    participant Scheduler as "System Scheduler"
    participant Notification as "Notification Service"
    participant CentralDB as "Central Database"
    participant Gateway as "SMS Gateway (External)"
    actor Caregiver

    Note over Scheduler,Gateway: FR12-FR13: Automated SMS Alerts
    Scheduler->>Notification: Trigger daily batch (00:00 AM)
    par Fetch recipient groups
      Notification->>CentralDB: Query due tomorrow (FR12)
      CentralDB-->>Notification: List of reminder recipients
      Notification->>CentralDB: Query missed > 48hrs (FR13)
      CentralDB-->>Notification: List of defaulter recipients
    end
    loop Process each caregiver
      Notification->>Notification: Localize message (Amharic/Oromiffa)
      alt Reminder
        Notification->>Gateway: Send(phone, "Reminder: Vaccine due")
      else Defaulter alert
        Notification->>Gateway: Send(phone, "Alert: Missed Appointment")
      end
      alt Network failure
        Gateway-->>Notification: 500 error
        Notification->>CentralDB: Log retry queue
        CentralDB-->>Notification: 200 OK (queued)
      else Accepted
        Gateway-->>Notification: 200 OK
      end
      Gateway-->>Caregiver: Deliver SMS (asynchronous)
    end
    Notification-->>Scheduler: Batch job complete
""",
    "figure-3-06-sequence-predictive-analytics.mmd": """sequenceDiagram
    actor PublicHealth as "Public Health Official"
    participant WebPortal as "Web Portal"
    participant Analytics as "Analytics Engine"
    participant ML as "ML Model Service"
    participant Weather as "Meteorological Service (External)"
    participant CentralDB as "Central Database"

    Note over PublicHealth,CentralDB: FR14-FR17: Outbreak Prediction and Visualization
    PublicHealth->>WebPortal: Request risk map (region: Somali)
    WebPortal->>Analytics: GET /prediction/risk-map
    par Data aggregation
      Analytics->>CentralDB: Fetch health data (coverage, zero-dose)
      CentralDB-->>Analytics: Health dataset
      Analytics->>Weather: Fetch rainfall/temp (last 30 days)
      Weather-->>Analytics: Weather dataset
    end
    Analytics->>ML: Execute models (health + weather)
    rect rgb(255, 248, 180)
    ML->>ML: Run KNN (spatial clustering)
    ML->>ML: Run XGBoost (cholera prediction)
    alt Risk score > threshold
      ML->>ML: Tag "High Risk Zone"
    else No data reporting
      ML->>ML: Tag "Silent District"
    end
    end
    ML-->>Analytics: Return GeoJSON vectors
    Analytics-->>WebPortal: Risk map data
    WebPortal->>WebPortal: Render heatmap layer
    WebPortal-->>PublicHealth: Display interactive map
""",
    "figure-3-07-sequence-reporting-and-interoperability.mmd": """sequenceDiagram
    actor Administrator
    participant Reporting as "Reporting Service"
    participant FHIR as "FHIR Mapper"
    participant Connector as "DHIS2 Connector"
    participant DHIS2 as "DHIS2 Platform (External)"
    participant CentralDB as "Central Database"

    Note over Administrator,CentralDB: FR18-FR21: Reporting and Interoperability
    Administrator->>Reporting: Generate monthly coverage report
    Reporting->>CentralDB: Query aggregated stats
    CentralDB-->>Reporting: Raw data
    Reporting->>Reporting: Generate PDF/CSV
    Reporting-->>Administrator: Download file

    Note over Reporting,CentralDB: Scheduled sync process
    Reporting->>Connector: Trigger weekly sync
    Connector->>CentralDB: Fetch unsynced records
    CentralDB-->>Connector: List of patients / immunizations
    loop For each record
      Connector->>FHIR: Map to FHIR resources
      FHIR->>FHIR: Map patient -> FHIR Patient
      FHIR->>FHIR: Map dose -> FHIR Immunization
      FHIR-->>Connector: Return FHIR bundle
      Connector->>DHIS2: POST /api/tracker (auth)
      alt Sync success
        DHIS2-->>Connector: 200 OK (import summary)
        Connector->>CentralDB: Update sync timestamp
      else Validation error
        DHIS2-->>Connector: 409 Conflict
        Connector->>CentralDB: Log error
      end
    end
    Connector-->>Reporting: Sync complete
""",
    "figure-3-08-state-user-account-lifecycle.mmd": """stateDiagram-v2
    [*] --> Inactive: Admin creates account
    Inactive --> Active: First login / change password
    Active --> Inactive: Logout / timeout
    Active --> Locked: 3 failed login attempts
    Locked --> Inactive: Admin unlocks account
    Active --> Deleted: Account deleted
    state Active {
      [*] --> Idle
      Idle --> Working: User interaction
      Working --> Idle: Task complete
    }
""",
    "figure-3-09-state-patient-registration-flow.mmd": """stateDiagram-v2
    [*] --> Draft: Health worker starts entry
    Draft --> Verifying: Submit data
    Verifying --> DuplicateFound: Match found
    Verifying --> Validated: No match (new patient)
    Validated --> Registered: Save to system
    DuplicateFound --> [*]: Reject & link
    Registered --> [*]
""",
    "figure-3-10-state-vaccination-appointment-lifecycle.mmd": """stateDiagram-v2
    [*] --> Scheduled
    Scheduled --> Due: Date arrived
    Scheduled --> Administered: Early dose
    Due --> Administered: On-time dose
    Due --> Overdue: 24 hours passed
    Overdue --> Defaulter: 7 days passed
    Defaulter --> Administered: Catch-up dose
    state Administered {
      [*] --> StoredLocally
      StoredLocally --> Synced: Internet connected
    }
    Administered --> [*]: Archived
""",
    "figure-3-11-state-sms-notification-flow.mmd": """stateDiagram-v2
    [*] --> Generated: Daily batch job
    Generated --> SentToGateway
    SentToGateway --> Delivered: Success (200 OK)
    SentToGateway --> Retrying: Failure (5xx)
    Retrying --> SentToGateway: Retry (max 3x)
    Retrying --> Failed: Max retries exceeded
    Delivered --> [*]
    Failed --> [*]
""",
    "figure-3-12-state-outbreak-alert-logic.mmd": """stateDiagram-v2
    [*] --> Monitoring
    Monitoring --> Processing: New data received
    state Processing {
      [*] --> RunningModels
      RunningModels --> CalculatingRisk
    }
    Processing --> Normal: Score < threshold
    Processing --> PotentialAlert: Score > threshold
    PotentialAlert --> ConfirmedOutbreak: Verified by official
    PotentialAlert --> FalseAlarm: Dismissed
    Normal --> Monitoring: Return to watch
    ConfirmedOutbreak --> [*]
    FalseAlarm --> [*]
""",
    "figure-3-13-state-data-export-and-interoperability-flow.mmd": """stateDiagram-v2
    [*] --> AssemblingData: Scheduled trigger
    AssemblingData --> MappingFHIR: Convert format
    MappingFHIR --> Validating: Check structure
    Validating --> Sending: Validation result / valid
    Validating --> Error: Invalid schema
    Sending --> Complete: DHIS2 accepts data
    Sending --> Error: Connection failed
    Complete --> [*]
    Error --> [*]
""",
    "figure-3-14-activity-user-management-and-security.mmd": """flowchart TD
    start([Start]) --> create["Admin creates role-based user account"]
    create --> valid{"Valid role and details?"}
    valid -- Yes --> assign["Assign unique user ID and role"]
    valid -- No --> reject["Reject creation and notify admin"] --> end([End])
    assign --> login["User attempts login"]
    login --> auth{"Authenticate credentials securely?"}
    auth -- Yes --> enforce["Enforce authorization rules based on role"]
    auth -- No --> deny["Deny access and log attempt"]
    deny --> recovery["User requests password recovery"]
    recovery --> identity{"Verify identity?"}
    identity -- Yes --> link["Send secure recovery link/token"]
    link --> reset["User resets password"] --> end
    identity -- No --> recoveryReject["Reject recovery and notify"] --> end
    enforce --> offline{"Offline mode?"}
    offline -- Yes --> local["Allow local actions and queue for sync"]
    local --> restored{"Connectivity restored?"}
    restored -- Yes --> sync["Synchronize with central server"] --> end
    restored -- No --> continue["Continue offline"] --> end
    offline -- No --> grant["Grant full access"] --> end
""",
    "figure-3-15-activity-patient-and-caregiver-registration.mmd": """flowchart TD
    start([Start]) --> init["Healthcare worker initiates registration"]
    init --> patient["Enter patient demographics<br/>DOB, sex, location"]
    patient --> caregiver["Enter caregiver details<br/>name, phone, relationship"]
    caregiver --> valid{"Validate input data"}
    valid -- Yes --> uid["Generate unique persistent identifier (UID)"]
    valid -- No --> correct["Prompt for corrections"] --> patient
    uid --> link["Link patient to caregiver entity"]
    link --> history["Initialize digital vaccination history record"]
    history --> offline{"Offline mode?"}
    offline -- Yes --> local["Store locally and queue for sync"]
    local --> restored{"Connectivity restored?"}
    restored -- Yes --> sync["Synchronize data with server"] --> end([End])
    restored -- No --> cont["Continue offline"] --> end
    offline -- No --> save["Save to central database securely"]
    save --> confirm["Confirm registration and notify caregiver via SMS"] --> end
""",
    "figure-3-16-activity-immunization-and-surveillance-management.mmd": """flowchart TD
    start([Start]) --> schedule["System generates vaccination schedule based on EPI guidelines"]
    schedule --> record["Healthcare worker records administered dose, batch ID, route, site"]
    record --> observe["Record surveillance observations e.g. AFP, rash, fever"]
    observe --> offline{"Offline mode?"}
    offline -- Yes --> local["Store data locally"]
    local --> restored{"Connectivity restored?"}
    restored -- Yes --> sync["Auto-synchronize with central server"]
    restored -- No --> continue["Continue offline operations"] --> end([End])
    offline -- No --> server["Save to central server immediately"]
    server --> analyze["Analyze patient record"]
    sync --> analyze
    analyze --> defaulter{"Is patient zero-dose or defaulter?"}
    defaulter -- Yes --> flag["Flag and alert health worker"]
    flag --> follow["Log for follow-up"] --> end
    defaulter -- No --> update["Update vaccination history"]
    update --> audit["Ensure data accuracy and audit log"] --> end
""",
    "figure-3-17-activity-notifications-and-alerts.mmd": """flowchart TD
    start([Start]) --> check["System checks vaccination schedule"]
    check --> upcoming{"Upcoming appointment?"}
    upcoming -- Yes --> remind["Send SMS reminder to caregiver"]
    remind --> success{"Delivery successful?"}
    success -- Yes --> log["Log notification sent"] --> end([End])
    success -- No --> retry["Retry SMS or queue for later"] --> end
    upcoming -- No --> missed["Check for missed appointments"]
    missed --> detected{"Missed appointment detected?"}
    detected -- Yes --> alert["Send follow-up SMS alert to caregiver"]
    alert --> delivered{"Delivery successful?"}
    delivered -- Yes --> monitor["Log alert sent and flag for monitoring"] --> end
    delivered -- No --> notify["Retry or notify health worker"] --> end
    detected -- No --> none["No action needed"] --> end
""",
    "figure-3-18-activity-predictive-analytics-and-decision-support.mmd": """flowchart TD
    start([Start]) --> collect["System collects vaccination, demographic, and environmental data"]
    collect --> weather["Ingest meteorological data: rainfall, temperature"]
    weather --> cluster["Apply spatial clustering algorithms to detect high-dropout/risk clusters"]
    cluster --> models["Execute prediction models: XGBoost/KNN using integrated data"]
    models --> risk{"Analyze for outbreak risks?"}
    risk -- Yes --> high["Identify high-risk areas and silent districts"]
    high --> viz["Generate visualizations: dashboards and maps for risk levels"]
    viz --> alerts["Provide decision-support alerts to health officials"] --> end([End])
    risk -- No --> monitoring["No immediate risk - continue monitoring"]
    monitoring --> log["Log for ongoing analysis"] --> end
""",
    "figure-3-19-activity-reporting-and-interoperability.mmd": """flowchart TD
    start([Start]) --> request["User requests configurable report on immunization/outbreak indicators"]
    request --> generate["Generate report using aggregated data"]
    generate --> export{"Export format specified?"}
    export -- Yes --> file["Export in standard formats e.g. CSV, PDF"]
    export -- No --> dashboard["Default to viewable dashboard"]
    file --> map["Map data to HL7 FHIR resources: patient, immunization, observation"]
    dashboard --> map
    map --> exchange["Exchange data with DHIS2 and national platforms"]
    exchange --> ok{"Interoperability successful?"}
    ok -- Yes --> log["Log exchange and ensure audit trail"] --> end([End])
    ok -- No --> retry["Handle error and retry exchange"] --> end
""",
    "figure-3-20-collaboration-diagram.mmd": """flowchart LR
    admin{{Administrator}}
    userMgmt[User Management Module]
    config[System Configuration Module]
    report[Report Generation Module]
    official[Public Health Official]
    epi[Epidemiology & Analytics Module]
    defaulter[Defaulter Monitoring Module]
    notification[Notification Service]
    sms[SMS Gateway]
    caregiver[Caregiver]
    vaccine[Vaccination Module]
    reg[Patient Registration Module]
    hw[Health Worker]
    outbreak[Outbreak Prediction & Alert Module]
    fhir[FHIR System]
    dhis2[DHIS2]

    admin -- "create/update/deleteUser(userData)" --> userMgmt
    admin -- "updateSystemSettings(settings)" --> config
    admin -- "generateReport(parameters)" --> report
    report -- "exportReport(format)" --> admin
    report -- "displayReport()" --> official
    official -- "viewDashboard(filters)" --> epi
    report -- "generateReport(parameters)" --> epi
    epi -- "getDefaulterData(region)" --> defaulter
    epi -- "updateRiskMap(regionRiskLevel)" --> outbreak
    outbreak -- "sendEpiData(diseaseIndicators)" --> epi
    outbreak -- "sendDefaulterData(childData, region)" --> defaulter
    defaulter -- "receiveAlert(alertMessage)" --> notification
    defaulter -- "scheduleReminderSMS(patientID, caregiverContact)" --> notification
    defaulter -- "sendMissedAppointmentAlert(patientID)" --> notification
    notification -- "sendSMS(reminderMessage)" --> sms
    notification -- "sendSMS(missedAppointmentAlert)" --> sms
    sms -- "receiveSMS(reminderMessage)" --> caregiver
    sms -- "receiveMissedAppointmentAlert()" --> caregiver
    vaccine -- "addToMonitoring(patientID, schedule)" --> defaulter
    reg -- "registerPatient(patientData)" --> hw
    vaccine -- "generateVaccinationSchedule(patientID)" --> dhis2
    vaccine -- "syncData(patientHealthData)" --> reg
    vaccine -- "exchangeData(patientHealthData)" --> fhir
    hw -- "generateOutbreakAlert(regionRiskLevel)" --> outbreak
""",
    "figure-4-01-layered-service-oriented-architecture.mmd": """flowchart TD
    hp[Health professional]
    cg[Care givers]

    subgraph presentation["Presentation layer"]
      web[Web application]
      sms[SMS]
    end

    subgraph application["Application layer"]
      userService[User Service]
      analyticsService[Analytics Service]
      vaccinationService[Vaccination Service]
      notificationService[Notification Service]
      predictionService[Prediction Service]
    end

    subgraph data["Data layer"]
      postgres[(PostgreSQL)]
      storage[(File Storage)]
    end

    subgraph integration["Integration layer"]
      dhis2[DHIS2]
      gateway[SMS Gateway]
    end

    hp --> web
    cg --> sms
    web --> application
    sms --> application
    application --> data
    data --> integration
""",
}


DIAGRAM_INDEX = [
    ("Supplementary", "Plan of Activities Gantt", "image5.png", "figure-1-01-plan-of-activities-gantt.mmd", "Approximation of the schedule image from Section 1.5."),
    ("Figure 3.1", "Use Case Diagram", "image1.png", "figure-3-01-use-case-diagram.mmd", "Rendered as a Mermaid flowchart because Mermaid has no native UML use-case syntax."),
    ("Figure 3.2", "Sequence Diagram – User Management and Security", "image17.png", "figure-3-02-sequence-user-management-and-security.mmd", "Mermaid sequence diagram."),
    ("Figure 3.3", "Sequence Diagram – Patient and Caregiver Registration", "image10.png", "figure-3-03-sequence-patient-registration.mmd", "Mermaid sequence diagram."),
    ("Figure 3.4", "Sequence Diagram – Immunization and Surveillance Management", "image19.png", "figure-3-04-sequence-immunization-and-surveillance.mmd", "Mermaid sequence diagram."),
    ("Figure 3.5", "Sequence Diagram – Notifications and Alerts", "image2.png", "figure-3-05-sequence-notifications-and-alerts.mmd", "Mermaid sequence diagram."),
    ("Figure 3.6", "Sequence Diagram – Predictive Analytics and Decision Support", "image4.png", "figure-3-06-sequence-predictive-analytics.mmd", "Mermaid sequence diagram."),
    ("Figure 3.7", "Sequence Diagram – Reporting and Interoperability", "image22.png", "figure-3-07-sequence-reporting-and-interoperability.mmd", "Mermaid sequence diagram."),
    ("Figure 3.8", "State Machine Diagram – User Account Lifecycle", "image13.png", "figure-3-08-state-user-account-lifecycle.mmd", "Mermaid state diagram."),
    ("Figure 3.9", "State Machine Diagram – Patient Registration Flow", "image7.png", "figure-3-09-state-patient-registration-flow.mmd", "Mermaid state diagram."),
    ("Figure 3.10", "State Machine Diagram – Vaccination Appointment Lifecycle", "image15.png", "figure-3-10-state-vaccination-appointment-lifecycle.mmd", "Mermaid state diagram."),
    ("Figure 3.11", "State Machine Diagram – SMS Notification Flow", "image11.png", "figure-3-11-state-sms-notification-flow.mmd", "Mermaid state diagram."),
    ("Figure 3.12", "State Machine Diagram – Outbreak Alert Logic", "image14.png", "figure-3-12-state-outbreak-alert-logic.mmd", "Mermaid state diagram."),
    ("Figure 3.13", "State Machine Diagram – Data Export and Interoperability Flow", "image8.png", "figure-3-13-state-data-export-and-interoperability-flow.mmd", "Mermaid state diagram."),
    ("Figure 3.14", "Activity Diagram – User Management and Security", "image18.png", "figure-3-14-activity-user-management-and-security.mmd", "Mermaid flowchart approximation."),
    ("Figure 3.15", "Activity Diagram – Patient and Caregiver Registration", "image20.png", "figure-3-15-activity-patient-and-caregiver-registration.mmd", "Mermaid flowchart approximation."),
    ("Figure 3.16", "Activity Diagram – Immunization and Surveillance Management", "image21.png", "figure-3-16-activity-immunization-and-surveillance-management.mmd", "Mermaid flowchart approximation."),
    ("Figure 3.17", "Activity Diagram – Notifications and Alerts", "image23.png", "figure-3-17-activity-notifications-and-alerts.mmd", "Mermaid flowchart approximation."),
    ("Figure 3.18", "Activity Diagram – Predictive Analytics and Decision Support", "image6.png", "figure-3-18-activity-predictive-analytics-and-decision-support.mmd", "Mermaid flowchart approximation."),
    ("Figure 3.19", "Activity Diagram – Reporting and Interoperability", "image12.png", "figure-3-19-activity-reporting-and-interoperability.mmd", "Mermaid flowchart approximation."),
    ("Figure 3.20", "Collaboration Diagram", "image9.png", "figure-3-20-collaboration-diagram.mmd", "Approximated as a Mermaid flowchart."),
    ("Figure 4.1", "Layered Service-Oriented Architecture", "image16.png", "figure-4-01-layered-service-oriented-architecture.mmd", "Mermaid flowchart."),
]


def write_mermaid_assets() -> None:
    for filename, body in MERMAID_TEMPLATES.items():
        target = MERMAID_DIR / filename
        if not target.exists():
            write_text(target, body.strip() + "\n")

    lines = [
        "# Diagram Source Index",
        "",
        "These Mermaid files are approximations of the report diagrams and are ready to paste into [mermaid.live](https://mermaid.live).",
        "",
        "| Figure | Diagram | Source Image | Mermaid File | Notes |",
        "| --- | --- | --- | --- | --- |",
    ]
    for figure, title, source_image, filename, note in DIAGRAM_INDEX:
        lines.append(
            f"| {figure} | {title} | `{source_image}` | [${filename}](./{filename}) | {note} |".replace("$", "")
        )

    write_text(MERMAID_DIR / "README.md", "\n".join(lines) + "\n")


def write_section_files(materialized: dict[str, str]) -> None:
    for key, content in materialized.items():
        target = SECTION_PATHS[key]
        write_text(target, AUTO_NOTE + content + "\n")


def write_indexes(manifest: dict[str, object]) -> None:
    manifest_path = DOC_ROOT / "REPORT_ASSEMBLY_MANIFEST.json"
    write_text(manifest_path, json.dumps(manifest, indent=2))

    lines = [
        "# Report Source Index",
        "",
        "This index maps the original report structure into the documentation workspace so the report is easy to reference, edit in parts, and reconstruct later.",
        "",
        "| Order | Section Key | File | Headings |",
        "| --- | --- | --- | --- |",
    ]

    for order, item in enumerate(manifest["ordered_files"], start=1):
        path = item["path"]
        headings = "; ".join(item["headings"])
        lines.append(f"| {order} | `{item['key']}` | [{path}]({path}) | {headings} |")

    lines.extend(
        [
            "",
            "## Rebuild",
            "",
            "Run the assembler to recreate a single markdown document:",
            "",
            "```bash",
            "python3 documentation/tools/assemble_report.py",
            "```",
            "",
        ]
    )
    write_text(DOC_ROOT / "REPORT_SOURCE_INDEX.md", "\n".join(lines) + "\n")


def main() -> None:
    source_html = resolve_source_html()
    ensure_source_assets(source_html)
    materialized, section_headings = build_sections(source_html)
    write_section_files(materialized)
    write_mermaid_assets()
    manifest = build_manifest(section_headings)
    write_indexes(manifest)


if __name__ == "__main__":
    main()
