#!/usr/bin/env python3
from __future__ import annotations

import os
import re
from pathlib import Path


DOC_ROOT = Path(__file__).resolve().parents[1]
BUILD_DIR = DOC_ROOT / "build"


AUTO_NOTE = (
    "<!-- Generated by documentation/tools/generate_chapter_drafts.py. "
    "Edit the draft file directly if you want to keep manual refinements, "
    "or update the generator and rerun it for repeatable changes. -->\n\n"
)


FIGURE_TO_MERMAID = {
    "3.1": "assets/diagrams/mermaid/figure-3-01-use-case-diagram.mmd",
    "3.2": "assets/diagrams/mermaid/figure-3-02-sequence-user-management-and-security.mmd",
    "3.3": "assets/diagrams/mermaid/figure-3-03-sequence-patient-registration.mmd",
    "3.4": "assets/diagrams/mermaid/figure-3-04-sequence-immunization-and-surveillance.mmd",
    "3.5": "assets/diagrams/mermaid/figure-3-05-sequence-notifications-and-alerts.mmd",
    "3.6": "assets/diagrams/mermaid/figure-3-06-sequence-predictive-analytics.mmd",
    "3.7": "assets/diagrams/mermaid/figure-3-07-sequence-reporting-and-interoperability.mmd",
    "3.8": "assets/diagrams/mermaid/figure-3-08-state-user-account-lifecycle.mmd",
    "3.9": "assets/diagrams/mermaid/figure-3-09-state-patient-registration-flow.mmd",
    "3.10": "assets/diagrams/mermaid/figure-3-10-state-vaccination-appointment-lifecycle.mmd",
    "3.11": "assets/diagrams/mermaid/figure-3-11-state-sms-notification-flow.mmd",
    "3.12": "assets/diagrams/mermaid/figure-3-12-state-outbreak-alert-logic.mmd",
    "3.13": "assets/diagrams/mermaid/figure-3-13-state-data-export-and-interoperability-flow.mmd",
    "3.14": "assets/diagrams/mermaid/figure-3-14-activity-user-management-and-security.mmd",
    "3.15": "assets/diagrams/mermaid/figure-3-15-activity-patient-and-caregiver-registration.mmd",
    "3.16": "assets/diagrams/mermaid/figure-3-16-activity-immunization-and-surveillance-management.mmd",
    "3.17": "assets/diagrams/mermaid/figure-3-17-activity-notifications-and-alerts.mmd",
    "3.18": "assets/diagrams/mermaid/figure-3-18-activity-predictive-analytics-and-decision-support.mmd",
    "3.19": "assets/diagrams/mermaid/figure-3-19-activity-reporting-and-interoperability.mmd",
    "3.20": "assets/diagrams/mermaid/figure-3-20-collaboration-diagram.mmd",
    "4.1": "assets/diagrams/mermaid/figure-4-01-layered-service-oriented-architecture.mmd",
}


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def read_markdown(relative_path: str) -> str:
    path = DOC_ROOT / relative_path
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if lines and lines[0].startswith("<!-- Auto-generated by documentation/tools/dissect_report.py"):
        text = "\n".join(lines[2:])
    return text.strip()


def retarget_links(text: str, source_relative_path: str, output_path: Path) -> str:
    source_path = DOC_ROOT / source_relative_path

    def replacer(match: re.Match[str]) -> str:
        target = match.group(1)
        if target.startswith(("http://", "https://", "#", "/")):
            return match.group(0)
        resolved = (source_path.parent / target).resolve()
        return f"]({Path(os.path.relpath(resolved, start=output_path.parent)).as_posix()})"

    return re.sub(r"\]\(([^)]+)\)", replacer, text)


def read_for_draft(relative_path: str, output_path: Path) -> str:
    return retarget_links(read_markdown(relative_path), relative_path, output_path)


def cleanup_spacing(text: str) -> str:
    text = re.sub(r"\n{3,}", "\n\n", text.strip())
    return text + "\n"


def sectionize_source(text: str) -> str:
    return re.sub(r"(?m)^# ", "## ", text)


def nest_standalone_doc(text: str) -> str:
    return re.sub(r"(?m)^(#{1,6}) ", lambda m: "#" + m.group(1) + " ", text)


def rel_link(from_path: Path, target_relative_to_doc_root: str) -> str:
    target = DOC_ROOT / target_relative_to_doc_root
    return Path(os.path.relpath(target, start=from_path.parent)).as_posix()


def add_mermaid_links(text: str, draft_path: Path) -> str:
    lines: list[str] = []
    for line in text.splitlines():
        lines.append(line)
        match = re.match(r"^\*Figure\s+(\d+\.\d+)[.:].*\*$", line.strip())
        if match:
            figure_key = match.group(1)
            mermaid_target = FIGURE_TO_MERMAID.get(figure_key)
            if mermaid_target:
                link = rel_link(draft_path, mermaid_target)
                lines.append(f"Mermaid source: [`{Path(mermaid_target).name}`]({link})")
    return "\n".join(lines)


def clean_front_matter() -> str:
    output_path = DOC_ROOT / "01-front-matter/front-matter-draft.md"
    cover = read_for_draft("01-front-matter/01-cover-and-title-page/report-source.md", output_path)
    ack = read_for_draft("01-front-matter/02-acknowledgement/report-source.md", output_path)
    abstract = read_for_draft("01-front-matter/04-abstract/report-source.md", output_path)
    toc_lists = read_for_draft("01-front-matter/03-table-of-contents-and-lists/report-source.md", output_path)

    abbreviations_text = toc_lists.split("# List of Abbreviations", 1)[-1].strip()
    matches = list(re.finditer(r"([A-Z][A-Za-z0-9]+)\s+[–-]\s+", abbreviations_text))
    pairs: list[tuple[str, str]] = []
    for index, match in enumerate(matches):
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(abbreviations_text)
        meaning = abbreviations_text[start:end].strip()
        pairs.append((match.group(1), meaning))
    abbrev_lines = ["# List of Abbreviations", ""]
    for abbr, meaning in pairs:
        abbrev_lines.append(f"- **{abbr}**: {meaning.strip()}")

    return cleanup_spacing(
        "\n\n".join(
            [
                cover,
                ack,
                "## Table of Contents, List of Tables, and List of Figures\n\nThese items should be generated automatically after final formatting of the report.",
                "\n".join(abbrev_lines),
                abstract,
            ]
        )
    )


def clean_chapter_one() -> str:
    output_path = DOC_ROOT / "02-chapter-1-introduction/chapter-draft.md"
    chapter = read_for_draft("02-chapter-1-introduction/chapter-source.md", output_path)
    s11 = sectionize_source(read_for_draft("02-chapter-1-introduction/01-statement-of-the-problem/report-source.md", output_path))
    s13 = sectionize_source(read_for_draft("02-chapter-1-introduction/03-scope-and-limitation/report-source.md", output_path))
    s14 = sectionize_source(read_for_draft("02-chapter-1-introduction/04-methodology/report-source.md", output_path))
    s15 = sectionize_source(read_for_draft("02-chapter-1-introduction/05-plan-of-activities/report-source.md", output_path))
    s16 = sectionize_source(read_for_draft("02-chapter-1-introduction/06-budget-required/report-source.md", output_path))
    s17 = sectionize_source(read_for_draft("02-chapter-1-introduction/07-significance-of-the-study/report-source.md", output_path))
    s18 = sectionize_source(read_for_draft("02-chapter-1-introduction/08-outline-of-the-study/report-source.md", output_path))

    objectives = """## 1.2 Objectives

### 1.2.1 General Objective

The general objective of this study is to design and develop a functional, secure, web- and SMS-based National Vaccination and Outbreak Monitoring System that centralizes vaccination data, improves real-time reporting, and strengthens outbreak prediction and response in Ethiopia [1], [2], [3].

### 1.2.2 Specific Objectives

- To design and implement a secure, scalable, and interoperable platform for managing vaccination data across healthcare facilities, aligned with HL7 FHIR and compatible with DHIS2 and eCHIS [4], [9].
- To digitize vaccination records and automate vaccination scheduling and caregiver reminders through SMS in order to reduce dropout and improve attendance [5].
- To provide administrators and public health officials with real-time dashboards, coverage analytics, and risk-oriented visualizations, including views for high-dropout areas and silent districts [1], [4].
- To integrate predictive analytics for early disease outbreak detection using vaccination, epidemiological, demographic, and environmental data.
  - To apply K-Nearest Neighbors (KNN) and eXtreme Gradient Boosting (XGBoost) to forecast high-risk areas for Measles [6], [7], [8].
  - To integrate meteorological indicators such as rainfall and temperature anomalies to support Cholera prediction [1].
  - To account for surveillance silence and contextual risk factors that can indicate Polio vulnerability in underserved areas [10].
- To evaluate the usability and practical effectiveness of the proposed system through testing and structured feedback from healthcare professionals [5].
"""

    draft = "\n\n".join([chapter, s11, objectives.strip(), s13, s14, s15, s16, s17, s18])
    return cleanup_spacing(draft)


def clean_chapter_two() -> str:
    output_path = DOC_ROOT / "03-chapter-2-literature-review/chapter-draft.md"
    chapter = read_for_draft("03-chapter-2-literature-review/chapter-source.md", output_path)
    s21 = sectionize_source(read_for_draft("03-chapter-2-literature-review/01-study-related-works/report-source.md", output_path))
    s22 = sectionize_source(read_for_draft("03-chapter-2-literature-review/02-milestones-and-gaps/report-source.md", output_path))
    s23 = sectionize_source(read_for_draft("03-chapter-2-literature-review/03-lessons-learned/report-source.md", output_path))

    draft = "\n\n".join([chapter, s21, s22, s23])
    draft = re.sub(r"(?m)^1\. eXtreme Gradient Boosting \(XGBoost\) in Disease Modeling$", "### 1. eXtreme Gradient Boosting (XGBoost) in Disease Modeling", draft)
    draft = re.sub(r"(?m)^2\. K-Nearest Neighbors \(KNN\) for Spatial Clustering$", "### 2. K-Nearest Neighbors (KNN) for Spatial Clustering", draft)
    return cleanup_spacing(draft)


def clean_dynamic_models_headings(text: str) -> str:
    replacements = {
        "1. User Management and Security": "##### 1. User Management and Security",
        "2. Patient and Caregiver Registration": "##### 2. Patient and Caregiver Registration",
        "3. Immunization and Surveillance Management": "##### 3. Immunization and Surveillance Management",
        "4. Notifications and Alerts": "##### 4. Notifications and Alerts",
        "5. Predictive Analytics and Decision Support": "##### 5. Predictive Analytics and Decision Support",
        "6. Reporting and Interoperability": "##### 6. Reporting and Interoperability",
        "1. User Account Lifecycle": "##### 1. User Account Lifecycle",
        "2. Patient Registration Flow": "##### 2. Patient Registration Flow",
        "3. Vaccination Appointment Lifecycle": "##### 3. Vaccination Appointment Lifecycle",
        "4. SMS Notification Flow": "##### 4. SMS Notification Flow",
        "5. Outbreak Alert Logic": "##### 5. Outbreak Alert Logic",
        "6. Data Export (Interoperability) Flow": "##### 6. Data Export (Interoperability) Flow",
        "1. Activity Diagram for User Management and Security": "##### 1. Activity Diagram for User Management and Security",
        "1. Activity Diagram for Patient and Caregiver Registration": "##### 2. Activity Diagram for Patient and Caregiver Registration",
        "1. Activity Diagram for Immunization and Surveillance Management": "##### 3. Activity Diagram for Immunization and Surveillance Management",
        "1. Activity Diagram for Notifications and Alerts": "##### 4. Activity Diagram for Notifications and Alerts",
        "1. Activity Diagram for Predictive Analytics and Decision Support": "##### 5. Activity Diagram for Predictive Analytics and Decision Support",
        "1. Activity Diagram for Reporting and Interoperability": "##### 6. Activity Diagram for Reporting and Interoperability",
    }
    for old, new in replacements.items():
        text = re.sub(rf"(?m)^{re.escape(old)}$", new, text)
    return text


def clean_chapter_three(draft_path: Path) -> str:
    parts = [
        read_for_draft("04-chapter-3-problem-analysis-and-modeling/chapter-source.md", draft_path),
        sectionize_source(read_for_draft("04-chapter-3-problem-analysis-and-modeling/01-existing-system-and-problems/report-source.md", draft_path)),
        sectionize_source(read_for_draft("04-chapter-3-problem-analysis-and-modeling/02-requirements-elicitation/report-source.md", draft_path)),
        sectionize_source(read_for_draft("04-chapter-3-problem-analysis-and-modeling/03-functional-requirements/report-source.md", draft_path)),
        sectionize_source(read_for_draft("04-chapter-3-problem-analysis-and-modeling/04-non-functional-requirements/report-source.md", draft_path)),
        sectionize_source(read_for_draft("04-chapter-3-problem-analysis-and-modeling/05-use-case-models/report-source.md", draft_path)),
        sectionize_source(read_for_draft("04-chapter-3-problem-analysis-and-modeling/06-dynamic-models/report-source.md", draft_path)),
        sectionize_source(read_for_draft("04-chapter-3-problem-analysis-and-modeling/07-model-validation/report-source.md", draft_path)),
    ]
    draft = "\n\n".join(parts)
    draft = clean_dynamic_models_headings(draft)
    draft = draft.replace("\n- Human actors who initiate actions or receive notifications:\n", "\n##### Human actors who initiate actions or receive notifications\n")
    draft = draft.replace("\n- System modules that process and store data:\n", "\n##### System modules that process and store data\n")
    draft = draft.replace("Report Generation Modul e", "Report Generation Module")
    draft = add_mermaid_links(draft, draft_path)
    return cleanup_spacing(draft)


def extract_er_diagram() -> str:
    db_design = read_markdown("05-chapter-4-system-design/04-database-design/NVOMS_DATABASE_DESIGN.md")
    match = re.search(r"```mermaid\n(.*?)```", db_design, re.DOTALL)
    if not match:
        return ""
    return "```mermaid\n" + match.group(1).strip() + "\n```"


def clean_chapter_four(draft_path: Path) -> str:
    chapter = """# Chapter Four: System Design

This chapter presents the detailed system design of the National Vaccination and Outbreak Monitoring System (NVOMS) for Ethiopia. The design translates the validated requirements and models from Chapter Three into a structured technical solution that supports secure data capture, vaccination tracking, predictive analytics, interoperability, and scalable public health decision support.
"""
    goals = sectionize_source(read_for_draft("05-chapter-4-system-design/01-overview-and-design-goals/report-source.md", draft_path))
    architecture = sectionize_source(read_for_draft("05-chapter-4-system-design/02-software-architecture/report-source.md", draft_path))
    subsystem = nest_standalone_doc(read_for_draft("05-chapter-4-system-design/04-database-design/NVOMS_SUBSYSTEM_DECOMPOSITION.md", draft_path))

    architecture = architecture.replace(
        "*Figure 4.0. System Architecture*",
        "*Figure 4.1: Layered Service-Oriented Architecture of the National Vaccination and Outbreak Monitoring System*",
    )
    architecture = architecture.replace("1. Architecture Overview (4-Tier Layered SOA)", "### Architecture Overview (4-Tier Layered SOA)")

    database_section = f"""## 4.3.3 Database Design

The database design of NVOMS is derived directly from the system requirements, the use-case model, the dynamic models, the layered service-oriented architecture, and the subsystem decomposition. PostgreSQL is selected as the core data platform because it provides strong relational integrity for vaccination tracking, support for structured interoperability payloads, and extensibility for analytical and geospatial data.

### Database Design Principles

- The patient registry remains the central point of the data model so that every vaccination, surveillance observation, and notification can be tied to a uniquely identified child.
- Vaccination schedules are stored separately from actual administered doses in order to support due, overdue, defaulter, catch-up, and administered states.
- Offline synchronization, SMS notification delivery, interoperability exchange logs, and audit trails are treated as first-class data structures rather than side effects.
- Prediction outputs and analytical summaries are separated from transactional tables so that reporting and risk scoring can scale without weakening core clinical integrity.
- Administrative geography is modeled hierarchically to support dashboards, hotspot analysis, and integration with national reporting structures.

### Core Entity Groups

- Geography and facility structure: administrative units and health facilities.
- Security and administration: users, roles, permissions, sessions, reset tokens, audit logs, and settings.
- Core registry: caregivers, patients, and duplicate review records.
- Immunization engine: vaccine definitions, EPI schedule versions and rules, patient schedules, vaccine batches, dose events, and schedule status history.
- Surveillance and alerts: surveillance reports, surveillance symptoms, and outbreak alerts.
- Notifications: message templates, SMS notifications, and notification attempts.
- Prediction and analytics: environmental observations, model registry, prediction runs, prediction scores, and defaulter clusters.
- Reporting and interoperability: report definitions, generated reports, integration jobs, DHIS2 sync records, and FHIR exchange logs.
- Offline sync: device registrations, sync batches, and sync batch items.

### High-Level ER View

{extract_er_diagram()}

### Database Design Artifacts

- Narrative database design: [NVOMS_DATABASE_DESIGN.md]({rel_link(draft_path, '05-chapter-4-system-design/04-database-design/NVOMS_DATABASE_DESIGN.md')})
- Implementation-ready PostgreSQL schema: [NVOMS_POSTGRESQL_SCHEMA.sql]({rel_link(draft_path, '05-chapter-4-system-design/04-database-design/NVOMS_POSTGRESQL_SCHEMA.sql')})
- Diagram-oriented DBML schema: [NVOMS_SCHEMA_DBML.dbml]({rel_link(draft_path, '05-chapter-4-system-design/04-database-design/NVOMS_SCHEMA_DBML.dbml')})
- Functional-requirements traceability: [NVOMS_REQUIREMENTS_VERIFICATION.md]({rel_link(draft_path, '05-chapter-4-system-design/04-database-design/NVOMS_REQUIREMENTS_VERIFICATION.md')})
"""

    design_verification = """## 4.4 Design Verification

The design was reviewed against the functional and non-functional requirements identified in Chapter Three. The resulting architecture and database structure support secure role-based access, atomic patient and caregiver registration, vaccination schedule generation, offline data capture and synchronization, SMS-based reminders, predictive analytics, interoperability with DHIS2 through FHIR-aligned mappings, and auditable reporting workflows. The design therefore satisfies the main operational needs of the proposed NVOMS prototype while remaining extensible for future national-scale deployment.
"""

    draft = "\n\n".join([chapter, goals, architecture, subsystem, database_section.strip(), design_verification.strip()])
    draft = draft.replace("SubSystem", "Subsystem")
    draft = add_mermaid_links(draft, draft_path)
    return cleanup_spacing(draft)


def clean_references() -> str:
    output_path = DOC_ROOT / "09-references/references-draft.md"
    refs = sectionize_source(read_for_draft("09-references/report-source.md", output_path))
    return cleanup_spacing(refs)


def rewrite_links_for_build(text: str, source_path: Path) -> str:
    def replacer(match: re.Match[str]) -> str:
        target = match.group(1)
        if target.startswith(("http://", "https://", "#", "/")):
            return match.group(0)
        resolved = (source_path.parent / target).resolve()
        try:
            rewritten = resolved.relative_to(DOC_ROOT)
        except ValueError:
            return match.group(0)
        return f"]({(Path('..') / rewritten).as_posix()})"

    return re.sub(r"\]\(([^)]+)\)", replacer, text)


def generate_build_document(draft_paths: list[Path]) -> None:
    chunks = [
        "<!-- Combined submission-oriented draft generated from chapter draft files. -->",
        "",
        "# National Vaccination and Outbreak Monitoring System for Ethiopia",
        "",
    ]
    for path in draft_paths:
        text = path.read_text(encoding="utf-8")
        lines = text.splitlines()
        if lines and lines[0].startswith("<!-- Generated by documentation/tools/generate_chapter_drafts.py"):
            text = "\n".join(lines[2:]).strip()
        chunks.append(rewrite_links_for_build(text, path))
        chunks.append("")

    write_text(BUILD_DIR / "NVOMS_Submission_Draft.md", "\n".join(chunks))


def main() -> None:
    front_matter_path = DOC_ROOT / "01-front-matter/front-matter-draft.md"
    chapter_one_path = DOC_ROOT / "02-chapter-1-introduction/chapter-draft.md"
    chapter_two_path = DOC_ROOT / "03-chapter-2-literature-review/chapter-draft.md"
    chapter_three_path = DOC_ROOT / "04-chapter-3-problem-analysis-and-modeling/chapter-draft.md"
    chapter_four_path = DOC_ROOT / "05-chapter-4-system-design/chapter-draft.md"
    references_path = DOC_ROOT / "09-references/references-draft.md"

    write_text(front_matter_path, AUTO_NOTE + clean_front_matter())
    write_text(chapter_one_path, AUTO_NOTE + clean_chapter_one())
    write_text(chapter_two_path, AUTO_NOTE + clean_chapter_two())
    write_text(chapter_three_path, AUTO_NOTE + clean_chapter_three(chapter_three_path))
    write_text(chapter_four_path, AUTO_NOTE + clean_chapter_four(chapter_four_path))
    write_text(references_path, AUTO_NOTE + clean_references())

    generate_build_document(
        [
            front_matter_path,
            chapter_one_path,
            chapter_two_path,
            chapter_three_path,
            chapter_four_path,
            references_path,
        ]
    )


if __name__ == "__main__":
    main()
