# Generated by Django 6.0.4 on 2026-04-27 16:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('patients', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveillanceReport',
            fields=[
                ('id', models.UUIDField(db_column='surveillance_report_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surveillance_category', models.CharField(choices=[('aefi', 'AEFI'), ('symptom', 'Symptom'), ('lab_follow_up', 'Lab Follow-Up')], max_length=20)),
                ('condition_type', models.CharField(max_length=80)),
                ('disease_suspected', models.CharField(blank=True, max_length=80, null=True)),
                ('onset_date', models.DateField()),
                ('body_temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=10, null=True)),
                ('follow_up_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('queued', 'Queued'), ('under_follow_up', 'Under Follow-Up'), ('closed', 'Closed')], default='submitted', max_length=20)),
                ('fhir_observation_id', models.CharField(blank=True, max_length=120, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('facility', models.ForeignKey(blank=True, db_column='facility_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveillance_reports', to='users.healthfacility')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='surveillance_reports', to='patients.patient')),
                ('reported_by', models.ForeignKey(blank=True, db_column='reported_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveillance_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'surveillance_reports',
            },
        ),
        migrations.CreateModel(
            name='OutbreakAlert',
            fields=[
                ('id', models.UUIDField(db_column='outbreak_alert_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disease_code', models.CharField(max_length=40)),
                ('alert_source', models.CharField(choices=[('prediction', 'Prediction'), ('surveillance', 'Surveillance'), ('manual', 'Manual')], max_length=20)),
                ('risk_probability', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('potential', 'Potential'), ('under_review', 'Under Review'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed'), ('false_alarm', 'False Alarm')], default='potential', max_length=20)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('unit', models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.PROTECT, related_name='outbreak_alerts', to='geography.administrativeunit')),
                ('verified_by', models.ForeignKey(blank=True, db_column='verified_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_alerts', to=settings.AUTH_USER_MODEL)),
                ('surveillance_report', models.ForeignKey(blank=True, db_column='surveillance_report_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbreak_alerts', to='surveillance.surveillancereport')),
            ],
            options={
                'db_table': 'outbreak_alerts',
            },
        ),
        migrations.CreateModel(
            name='FollowUpAction',
            fields=[
                ('id', models.UUIDField(db_column='follow_up_action_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_taken', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed')], default='open', max_length=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_to', models.ForeignKey(blank=True, db_column='assigned_to_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(db_column='surveillance_report_id', on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='surveillance.surveillancereport')),
            ],
            options={
                'db_table': 'follow_up_actions',
            },
        ),
        migrations.CreateModel(
            name='SurveillanceSymptom',
            fields=[
                ('id', models.UUIDField(db_column='surveillance_symptom_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptom_code', models.CharField(max_length=40)),
                ('symptom_label', models.CharField(max_length=120)),
                ('is_present', models.BooleanField(default=True)),
                ('observation_value', models.CharField(blank=True, max_length=120, null=True)),
                ('report', models.ForeignKey(db_column='surveillance_report_id', on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='surveillance.surveillancereport')),
            ],
            options={
                'db_table': 'surveillance_symptoms',
            },
        ),
    ]
