# Generated by Django 4.2.30 on 2026-05-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveillancereport',
            name='fhir_resource_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
