# Generated by Django 4.2.30 on 2026-05-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0003_surveillancereport_local_client_record_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveillancereport',
            name='clinical_outcome',
            field=models.CharField(blank=True, choices=[('recovered', 'Recovered'), ('hospitalized', 'Hospitalized'), ('transferred', 'Transferred'), ('deceased', 'Deceased')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='lab_result_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('positive', 'Positive'), ('negative', 'Negative')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='lab_sample_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='lab_test_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
