# Generated by Django 4.2.30 on 2026-05-17 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0002_scheduleregenerationjob'),
        ('immunizations', '0004_immunizationevent_disease_and_more'),
        ('surveillance', '0004_surveillancereport_clinical_outcome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveillancereport',
            name='aefi_immunization_event',
            field=models.ForeignKey(blank=True, db_column='aefi_immunization_event_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aefi_case_reports', to='immunizations.immunizationevent'),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='aefi_vaccine',
            field=models.ForeignKey(blank=True, db_column='aefi_vaccine_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aefi_case_reports', to='vaccines.vaccinedefinition'),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='aefi_vaccine_batch',
            field=models.ForeignKey(blank=True, db_column='aefi_vaccine_batch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aefi_case_reports', to='vaccines.vaccinebatch'),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='clinical_outcome_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='lab_result_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='lab_result_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='next_follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='outcome_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='specimen_collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='specimen_status',
            field=models.CharField(choices=[('not_collected', 'Not Collected'), ('pending', 'Pending'), ('collected', 'Collected'), ('sent', 'Sent'), ('received', 'Received')], default='not_collected', max_length=20),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='specimen_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='vaccination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveillancereport',
            name='vaccine_dose_label',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='surveillancereport',
            name='clinical_outcome',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('recovering', 'Recovering'), ('recovered', 'Recovered'), ('hospitalized', 'Hospitalized'), ('referred', 'Referred'), ('transferred', 'Transferred'), ('deceased', 'Deceased')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='surveillancereport',
            name='lab_result_status',
            field=models.CharField(blank=True, choices=[('not_sent', 'Not Sent'), ('pending', 'Pending'), ('positive', 'Positive'), ('negative', 'Negative'), ('inconclusive', 'Inconclusive')], max_length=20, null=True),
        ),
    ]
