# Generated by Django 4.2.30 on 2026-05-03 04:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteorologicalObservation',
            fields=[
                ('id', models.UUIDField(db_column='environmental_observation_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observation_date', models.DateField()),
                ('rainfall_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('source', models.CharField(default='manual', max_length=80)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unit', models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.CASCADE, related_name='meteorological_observations', to='geography.administrativeunit')),
            ],
            options={
                'db_table': 'meteorological_observations',
                'ordering': ['-observation_date', 'unit__name'],
                'unique_together': {('unit', 'observation_date', 'source')},
            },
        ),
    ]
