# Generated by Django 6.0.4 on 2026-04-26 14:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('users', '0001_initial'),
        ('vaccines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVaccinationSchedule',
            fields=[
                ('id', models.UUIDField(db_column='patient_schedule_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('pending', 'Pending'), ('due_soon', 'Due Soon'), ('due_today', 'Due Today'), ('overdue', 'Overdue'), ('defaulter', 'Defaulter'), ('administered', 'Administered'), ('exempt', 'Exempt'), ('cancelled', 'Cancelled')], default='scheduled', max_length=16)),
                ('status_reason', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='patients.patient')),
                ('schedule_rule', models.ForeignKey(db_column='schedule_rule_id', on_delete=django.db.models.deletion.PROTECT, related_name='schedule_slots', to='vaccines.epischedulerule')),
                ('vaccine', models.ForeignKey(db_column='vaccine_id', on_delete=django.db.models.deletion.PROTECT, related_name='schedule_slots', to='vaccines.vaccinedefinition')),
            ],
            options={
                'db_table': 'patient_vaccination_schedules',
                'unique_together': {('patient', 'schedule_rule')},
            },
        ),
        migrations.CreateModel(
            name='ImmunizationEvent',
            fields=[
                ('id', models.UUIDField(db_column='immunization_event_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('administered_at', models.DateTimeField()),
                ('administration_route', models.CharField(blank=True, max_length=40, null=True)),
                ('administration_site', models.CharField(blank=True, max_length=40, null=True)),
                ('event_status', models.CharField(choices=[('administered', 'Administered'), ('wasted', 'Wasted'), ('refused', 'Refused'), ('contraindicated', 'Contraindicated')], default='administered', max_length=20)),
                ('source_channel', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('synced', 'Synced')], default='online', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('administered_by', models.ForeignKey(blank=True, db_column='administered_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_events', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, db_column='facility_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immunization_events', to='users.healthfacility')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='immunization_events', to='patients.patient')),
                ('vaccine', models.ForeignKey(db_column='vaccine_id', on_delete=django.db.models.deletion.PROTECT, related_name='immunization_events', to='vaccines.vaccinedefinition')),
                ('vaccine_batch', models.ForeignKey(blank=True, db_column='vaccine_batch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immunization_events', to='vaccines.vaccinebatch')),
                ('schedule_slot', models.ForeignKey(blank=True, db_column='patient_schedule_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='immunizations.patientvaccinationschedule')),
            ],
            options={
                'db_table': 'immunization_events',
            },
        ),
    ]
