# Generated by Django 6.0.4 on 2026-04-26 15:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immunizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='immunizationevent',
            name='local_client_record_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='ScheduleStatusEvent',
            fields=[
                ('id', models.UUIDField(db_column='status_event_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=16, null=True)),
                ('to_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('pending', 'Pending'), ('due_soon', 'Due Soon'), ('due_today', 'Due Today'), ('overdue', 'Overdue'), ('defaulter', 'Defaulter'), ('administered', 'Administered'), ('exempt', 'Exempt'), ('cancelled', 'Cancelled')], max_length=16)),
                ('changed_by_process', models.CharField(blank=True, max_length=80, null=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, db_column='changed_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_status_changes', to=settings.AUTH_USER_MODEL)),
                ('schedule_slot', models.ForeignKey(db_column='patient_schedule_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='immunizations.patientvaccinationschedule')),
            ],
            options={
                'db_table': 'schedule_status_events',
            },
        ),
    ]
