# Generated by Django 4.2.30 on 2026-05-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immunizations', '0002_immunizationevent_local_client_record_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunizationevent',
            name='dhis2_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='immunizationevent',
            name='fhir_resource_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
