# Generated by Django 4.2.30 on 2026-05-17 04:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_caregiver_local_client_record_id_and_more'),
        ('immunizations', '0003_immunizationevent_dhis2_synced_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunizationevent',
            name='disease',
            field=models.CharField(blank=True, choices=[('measles', 'Measles'), ('polio', 'Polio'), ('cholera', 'Cholera')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='immunizationevent',
            name='disease_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='immunizationevent',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PatientDiseaseSchedule',
            fields=[
                ('id', models.UUIDField(db_column='patient_disease_schedule_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disease', models.CharField(choices=[('measles', 'Measles'), ('polio', 'Polio'), ('cholera', 'Cholera')], max_length=20)),
                ('current_due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('scheduled', 'Scheduled'), ('due_soon', 'Due Soon'), ('due_today', 'Due Today'), ('overdue', 'Overdue'), ('protected', 'Protected'), ('completed', 'Completed'), ('refused', 'Refused'), ('contraindicated', 'Contraindicated')], default='not_started', max_length=20)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_outcome_event', models.ForeignKey(blank=True, db_column='last_outcome_event_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_disease_schedules', to='immunizations.immunizationevent')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='disease_schedules', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_disease_schedules',
                'unique_together': {('patient', 'disease')},
            },
        ),
    ]
