# Generated by Django 6.0.4 on 2026-04-29 14:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.UUIDField(db_column='report_definition_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_code', models.CharField(max_length=60, unique=True)),
                ('report_name', models.CharField(max_length=160)),
                ('report_scope', models.CharField(choices=[('facility', 'Facility'), ('woreda', 'Woreda'), ('region', 'Region'), ('national', 'National')], max_length=10)),
                ('definition_spec', models.JSONField(blank=True, null=True)),
                ('default_parameters', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_definitions',
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(db_column='generated_report_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV')], default='pdf', max_length=4)),
                ('generation_status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=12)),
                ('parameter_payload', models.JSONField(blank=True, null=True)),
                ('file_uri', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(blank=True, db_column='facility_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='users.healthfacility')),
                ('requested_by', models.ForeignKey(blank=True, db_column='requested_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_reports', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, db_column='unit_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='geography.administrativeunit')),
                ('report_definition', models.ForeignKey(db_column='report_definition_id', on_delete=django.db.models.deletion.PROTECT, related_name='generated_reports', to='reports.reportdefinition')),
            ],
            options={
                'db_table': 'generated_reports',
            },
        ),
    ]
